# Sample only
---
all:
  children:
    kubernetes:
      children:
        control_plane:
          hosts:
            control-plane-01:
              ansible_host: 192.168.56.10
        workers:
          hosts:
            worker-01:
              ansible_host: 192.168.56.11
