---
name: ci
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  checks:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7
      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.12.11
      - name: Install Deps
        run: pip install -r requirements-dev.txt;
      - name: MAKE Sure `Make` Is Installed
        run: sudo apt install -y make;
      - name: Install Dependencies For Test Scripts
        run: |
          # Install GPG for fixture generation.
          sudo apt install -y gnupg;
      - name: Run Linter
        run: make run-linter;
      - name: Run Molecule Tests
        run: |
          make run-debian-tests;
          make run-ubuntu-tests;
